In [3]:
import numpy as np
#numpy的版本和配置说明 
print(np.__version__)
np.show_config()

1.16.2
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/zhou/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/zhou/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/zhou/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', '

In [6]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


In [11]:
#函数说明文档
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [12]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [17]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [18]:
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [19]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [20]:
#非0索引
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [21]:
#单位矩阵
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.27795966 0.5397169  0.41405999]
  [0.05872711 0.972823   0.37996428]
  [0.40124997 0.67207011 0.63934709]]

 [[0.25323609 0.75173831 0.2540975 ]
  [0.13494178 0.32047528 0.76917182]
  [0.74666742 0.52403602 0.58250538]]

 [[0.45621865 0.08845988 0.11667579]
  [0.39248187 0.41711666 0.64509801]
  [0.24629013 0.51476956 0.51418373]]]


In [25]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.00042497938584373784 0.9898762173946102


In [26]:
#平均值
Z = np.random.random(30)
m = Z.mean()
print(m)

0.46936179259503324


In [27]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [4]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [6]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


In [16]:
Z = np.diag(1+np.arange(4),k=-1)
X = np.diag(1+np.arange(4))
print(Z)
print(X)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [8]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [9]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [10]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [11]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[0.79444126 0.8229734  0.68093365 0.3925199  0.15370779]
 [0.7145568  0.70874372 0.39471799 0.         0.95955005]
 [0.91340504 0.90572917 0.6131791  0.12682335 0.93164264]
 [0.95987761 1.         0.82952217 0.05209039 0.71189625]
 [0.38660754 0.11458694 0.40961348 0.71541247 0.86024841]]


In [12]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [13]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [14]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [15]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [23]:
Z = np.arange(5)
Z ** Z  

array([  1,   1,   4,  27, 256], dtype=int32)

In [21]:
Z = np.arange(5)
2 << Z >> 2 

array([0, 1, 2, 4, 8], dtype=int32)

In [27]:
Z = np.arange(5)
1j*Z   # legal

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j])

In [28]:
Z = np.arange(5)
Z/1/1   # legal

array([0., 1., 2., 3., 4.])

In [29]:
Z = np.arange(5)
Z<Z>Z    # false

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [31]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\zhou\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\zhou\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


In [32]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[6 7 8]


In [45]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)


with np.errstate(divide='ignore'):
 Z = np.ones(1) / 0


In [46]:
np.sqrt(-1) == np.emath.sqrt(-1) 

C:\Users\zhou\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

In [47]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print ("Yesterday is " + str(yesterday))
print ("Today is " + str(today))
print ("Tomorrow is "+ str(tomorrow))

Yesterday is 2019-06-22
Today is 2019-06-23
Tomorrow is 2019-06-24


In [48]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [49]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)

array([3., 3., 3.])

In [57]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [58]:
#提取一个随机数组的整数部分
Z = np.random.uniform(0,10,10)
print (Z - Z%1)

[6. 0. 2. 9. 8. 0. 5. 2. 0. 6.]


In [59]:
print (np.floor(Z))

[6. 0. 2. 9. 8. 0. 5. 2. 0. 6.]


In [60]:
print (np.ceil(Z)-1)

[6. 0. 2. 9. 8. 0. 5. 2. 0. 6.]


In [61]:
print (Z.astype(int))

[6 0 2 9 8 0 5 2 0 6]


In [62]:
print (np.trunc(Z))

[6. 0. 2. 9. 8. 0. 5. 2. 0. 6.]


In [63]:
Z = np.zeros((5,5))
Z += np.arange(5)
print (Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [64]:
def generate():
    for x in range(10):         
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print (Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [66]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print (Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [67]:
 Z= np.random.random(10)
 Z.sort()
 print (Z)

[0.02092876 0.0964518  0.15799575 0.16735354 0.17313066 0.34225361
 0.47511647 0.60090016 0.67116082 0.843761  ]


In [68]:
#对于一个小数组，用比 np.sum更快的方式对其求和
Z = np.arange(10)
np.add.reduce(Z)

45

In [69]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

False


In [71]:
# 方法2
# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False


In [72]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

In [73]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print (R)
print (T)

[0.67242453 0.9675191  1.05912662 1.25996011 0.3230587  1.21806962
 0.67476128 0.72829124 0.90335642 0.37342034]
[1.10551747 0.66952354 1.17463571 0.90116767 0.97623928 0.77751113
 1.3805955  0.76200116 0.36406108 1.06436961]


In [75]:
Z = np.random.random(10)
Z[Z.argmax()] = 1
print (Z)

[0.42109615 0.57423641 0.37491908 1.         0.15153754 0.70128219
 0.33050002 0.62231151 0.72402557 0.22563922]


In [76]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [77]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


In [78]:
 for dtype in [np.int8, np.int32, np.int64]:
     print(np.iinfo(dtype).min)
     print(np.iinfo(dtype).max)

 for dtype in [np.float32, np.float64]:
     print(np.finfo(dtype).min)
     print(np.finfo(dtype).max)
     print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


ValueError: threshold must be numeric and non-NAN, try sys.maxsize for untruncated representation

In [92]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print (Z[index])

65


In [94]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                   ('y', float, 1)]),
                    ('color',    [ ('r', float, 1),
                                   ('g', float, 1),
                                   ('b', float, 1)])])
print (Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ... ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


In [96]:
Z = np.random.random((100,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print (D)

# 方法2
# Much faster with scipy
# import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
# import scipy.spatial
# D = scipy.spatial.distance.cdist(Z,Z)
# print (D)

[[0.         0.48179261 0.0823584  ... 0.18805624 0.6322394  0.65877115]
 [0.48179261 0.         0.40270923 ... 0.66602903 0.39294874 0.43561232]
 [0.0823584  0.40270923 0.         ... 0.26342502 0.55775515 0.61671057]
 ...
 [0.18805624 0.66602903 0.26342502 ... 0.         0.76249403 0.8298374 ]
 [0.6322394  0.39294874 0.55775515 ... 0.76249403 0.         0.82814226]
 [0.65877115 0.43561232 0.61671057 ... 0.8298374  0.82814226 0.        ]]


In [97]:
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)
print (Z)

[0. 1. 2. ... 7. 8. 9.]


In [98]:
#读取文件
#np.genfromtxt

In [102]:
#对于numpy数组，enumerate的等价操作
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [103]:
#通用的二维Gaussian-like数组 
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print (G)

[[0.36787944 0.44822088 0.51979489 ... 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 ... 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 ... 0.73444367 0.63331324 0.51979489]
 ...
 [0.51979489 0.63331324 0.73444367 ... 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 ... 0.63331324 0.54610814 0.44822088]
 [0.36787944 0.44822088 0.51979489 ... 0.51979489 0.44822088 0.36787944]]


In [104]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print (Z)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [105]:
X = np.random.rand(5, 10)
# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

# 方法2
# Older versions of numpy
# Y = X - X.mean(axis=1).reshape(-1, 1)
# print (Y)

[[-0.33734321 -0.10791654  0.21989483 ...  0.01834893  0.17846516
   0.28981081]
 [ 0.41156767 -0.30926011  0.05700477 ... -0.28697486  0.09492288
  -0.26874922]
 [-0.07515445 -0.15997134 -0.20999957 ... -0.0849786  -0.06121904
  -0.01784098]
 [-0.26758063 -0.0882328  -0.05426025 ...  0.21272851  0.06520493
  -0.23457956]
 [ 0.46763016  0.34373767 -0.46559385 ...  0.0194449  -0.38266247
   0.06993295]]


In [106]:
Z = np.random.randint(0,10,(3,3))
print (Z)
print (Z[Z[:,1].argsort()])

[[3 6 1]
 [3 4 7]
 [6 6 1]]
[[3 4 7]
 [3 6 1]
 [6 6 1]]


In [107]:
#检查一个二维数组是否有空列
Z = np.random.randint(0,3,(3,10))
print ((~Z.any(axis=0)).any())

True


In [108]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print (m)

0.5308885581186162


In [109]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: 
     z[...] = x + y
print (it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [113]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
             obj = np.asarray(array).view(cls)
             obj.name = name
             return obj
    def __array_finalize__(self, obj):
             if obj is None: return
             self.info = getattr(obj, 'name', "no name")
Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [114]:
#一个给定的向量，如何对由第二个向量索引的每个元素加1(小心重复的索引)
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)
# 方法2
# np.add.at(Z, I, 1)
# print(Z)

[4. 3. 3. ... 1. 1. 3.]


In [115]:
#根据索引列表(I)，将向量(X)的元素累加到数组(F)
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print (F)

[0. 7. 0. ... 0. 0. 3.]


In [116]:
#考虑一个(dtype=ubyte) 的 (w,h,3)图像，计算其唯一颜色的数量
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
#Note that we should compute 256*256 first. 
#Otherwise numpy will only promote F.dtype to 'uint16' and overfolw will occur
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print (n)

8


In [117]:
#考虑一个四维数组，一次性计算出最后两个轴(axis)的和
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print (sum)
# 方法2
# sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
# print (sum)

[[44 48 45 59]
 [54 56 53 60]
 [65 52 50 49]]


In [118]:
#一个一维向量D，使用相同大小的向量S来计算D子集的均值
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print (D_means)

# 方法2
# import pandas as pd
# print(pd.Series(D).groupby(S).mean())

[0.41582057 0.51519352 0.5032884  ... 0.46151737 0.49577595 0.45787307]


In [119]:
#获得点积 dot prodcut的对角线
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
#slow version
np.diag(np.dot(A, B))

# 方法2
# Fast version
# np.sum(A * B.T, axis=1)
# 方法3
# Faster version
# np.einsum("ij,ji->i", A, B)

array([1.75428468, 1.49924844, 0.71890114, 1.28919791, 0.10614813])

In [120]:
#一个向量[1,2,3,4,5],建立一个新的向量，在这个新向量中每个值之间有3个连续的零
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print (Z0)

[1. 0. 0. ... 0. 0. 5.]


In [121]:
#一个维度(5,5,3)的数组，如何将其与一个(5,5)的数组相乘
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print (A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [122]:
#如何对一个数组中任意两行做交换
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print (A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [123]:
#一个可以描述10个三角形的triplets，找到可以分割全部三角形的line segment
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print (G)

[( 0, 54) ( 0, 57) ( 5, 21) ... (83, 86) (87, 89) (96, 98)]


In [124]:
#给定一个二进制的数组C，产生一个数组A满足np.bincount(A)==C
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print (A)

[1 1 2 ... 4 4 6]


In [125]:
#通过滑动窗口计算一个数组的平均数
def moving_average(a, n=3) :
     ret = np.cumsum(a, dtype=float)
     ret[n:] = ret[n:] - ret[:-n]
     return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3. ... 16. 17. 18.]


In [126]:
#考虑一维数组Z，构建一个二维数组，其第一行为（Z [0]，Z [1]，Z [2]），每个后续行移1（最后一行应为（Z [-3]，Z[-2]，Z[-1]）
from numpy.lib import stride_tricks

def rolling(a, window):
     shape = (a.size - window + 1, window)
     strides = (a.itemsize, a.itemsize)
     return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)

print (Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 ...
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [129]:
#对布尔值取反，或者原位(in-place)改变浮点数的符号(sign)
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

array([1, 1, 0, ..., 0, 1, 1])

In [128]:
Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.82935572, -0.97684122, -0.08884902, ..., -0.05643743,
        0.73009099, -0.50462737])

In [130]:
#考虑两组点集P0和P1去描述一组线(二维)和一个点p,计算点p到每一条线 i (P0[i],P1[i])的距离
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))

print (distance(P0, P1, p))

[ 5.98610187 13.15607108  2.95537601 ...  4.62824924 11.74921443
  1.01073491]


In [131]:
#考虑两组点集P0和P1去描述一组线(二维)和一组点集P，计算每一个点 j(P[j]) 到每一条线 i (P0[i],P1[i])的距离
# based on distance function from previous question
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print (np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 8.25717804  3.64638286  6.32981169 ... 12.22363639  0.42382446
   0.87189864]
 [ 0.98659875  4.9517348   8.95376723 ...  2.2733202   8.076402
   2.99997516]
 [17.99519514  1.31700423  8.5652863  ... 21.70387975 10.09810919
   8.37684493]
 ...
 [ 5.98359294  2.90721711  3.70770817 ...  9.56717064  2.03190615
   2.29432006]
 [ 1.96872369 10.70394851  9.1489898  ...  7.00093891  5.42356767
   8.34015952]
 [ 9.86055804  6.30302565  3.40709166 ... 11.65277287  1.0687246
   4.19665643]]


In [132]:
#考虑一个任意数组，编写一个函数，提取具有固定形状的子部分并以给定元素为中心（必要时填充值为pad）
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print (Z)
print (R)

[[7 7 4 ... 2 7 6]
 [0 7 8 ... 9 0 4]
 [6 7 0 ... 1 1 7]
 ...
 [6 5 9 ... 1 2 0]
 [3 9 3 ... 8 1 0]
 [3 1 6 ... 2 8 9]]
[[0 0 0 0 0]
 [0 7 7 4 1]
 [0 0 7 8 4]
 [0 6 7 0 1]
 [0 9 2 6 7]]


C:\Users\zhou\Anaconda3\lib\site-packages\ipykernel_launcher.py:24: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


In [133]:
#一个数组Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14],如何生成一个数组R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ...,[11,12,13,14]]? 
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print (R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 ...
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [134]:
#计算一个矩阵的秩(
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print (rank)

10


In [135]:
Z = np.random.randint(0,10,50)
print (np.bincount(Z).argmax())

9


In [136]:
#从一个10x10的矩阵中提取出连续的3x3区块
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print (C)

[[[[0 0 0]
   [3 1 1]
   [0 0 4]]

  [[0 0 2]
   [1 1 3]
   [0 4 1]]

  [[0 2 4]
   [1 3 4]
   [4 1 1]]

  ...

  [[4 0 0]
   [0 4 2]
   [1 0 3]]

  [[0 0 1]
   [4 2 2]
   [0 3 0]]

  [[0 1 4]
   [2 2 3]
   [3 0 1]]]


 [[[3 1 1]
   [0 0 4]
   [2 3 1]]

  [[1 1 3]
   [0 4 1]
   [3 1 4]]

  [[1 3 4]
   [4 1 1]
   [1 4 1]]

  ...

  [[0 4 2]
   [1 0 3]
   [1 4 4]]

  [[4 2 2]
   [0 3 0]
   [4 4 3]]

  [[2 2 3]
   [3 0 1]
   [4 3 0]]]


 [[[0 0 4]
   [2 3 1]
   [2 1 2]]

  [[0 4 1]
   [3 1 4]
   [1 2 2]]

  [[4 1 1]
   [1 4 1]
   [2 2 0]]

  ...

  [[1 0 3]
   [1 4 4]
   [3 0 4]]

  [[0 3 0]
   [4 4 3]
   [0 4 0]]

  [[3 0 1]
   [4 3 0]
   [4 0 0]]]


 ...


 [[[2 3 3]
   [0 3 0]
   [4 4 0]]

  [[3 3 1]
   [3 0 1]
   [4 0 2]]

  [[3 1 3]
   [0 1 3]
   [0 2 0]]

  ...

  [[0 2 3]
   [2 3 0]
   [2 4 2]]

  [[2 3 4]
   [3 0 2]
   [4 2 3]]

  [[3 4 2]
   [0 2 3]
   [2 3 4]]]


 [[[0 3 0]
   [4 4 0]
   [3 3 1]]

  [[3 0 1]
   [4 0 2]
   [3 1 0]]

  [[0 1 3]
   [0 2 0]
   [1 0 4]]

  ...

  [[2

In [138]:
 #创建一个满足 Z[i,j] == Z[j,i]的子类
class Symetric(np.ndarray):
     def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 33
print (S)

[[ 4  2  4  8  4]
 [ 2  8  3  7  6]
 [ 4  3  9 33  9]
 [ 8  7 33  9  6]
 [ 4  6  9  6  2]]


In [141]:
#p个 nxn 矩阵和一组形状为(n,1)的向量，直接计算p个矩阵的乘积(n,1)
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print (S)
#It works, because:
#M is (p,n,n)
#V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

[[200.]
 [200.]
 [200.]
 ...
 [200.]
 [200.]
 [200.]]


In [142]:
#对于一个16x16的数组，得到一个区域(block-sum)的和(区域大小为4x4)
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print (S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [143]:
#利用numpy数组实现Game of Life
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print (Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [144]:
#找到一个数组的第n个最大值
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# 方法2
# Fast
# print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]


In [145]:
#给定任意个数向量，创建笛卡尔积(每一个元素的每一种组合)
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 ...
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [146]:
#从一个正常数组创建记录数组(record array)
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print (R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [148]:
#一个大向量Z, 用三种不同的方法计算它的立方
x = np.random.rand()
np.power(x,3)
# 方法2
# x*x*x
# 方法3
# np.einsum('i,i,i->i',x,x,x)

0.06795301756319086

In [149]:
#两个形状分别为(8,3) 和(2,2)的数组A和B. 在数组A中找到满足包含B中元素的行？(不考虑B中每行元素顺序)
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print (rows)


[0 1 2 ... 5 6 7]


In [152]:
#一个10x3的矩阵，分解出有不全相同值的行 (如 [2,2,3])
Z = np.random.randint(0,5,(10,3))
print ('Z:',Z)

# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print ('U:',U)
# 方法2
# soluiton for numerical arrays only, will work for any number of columns in Z
# U = Z[Z.max(axis=1) != Z.min(axis=1),:]
# print (U)

Z: [[0 0 2]
 [2 2 4]
 [3 1 0]
 ...
 [1 0 3]
 [4 2 3]
 [4 1 1]]
U: [[0 0 2]
 [2 2 4]
 [3 1 0]
 ...
 [1 0 3]
 [4 2 3]
 [4 1 1]]


In [153]:
#将一个整数向量转换为matrix binary的表现形式
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])
# 方法2
# print (np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]]


In [154]:
#给定一个二维数组，提取出唯一的(unique)行
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print (uZ)

[[0 0 0]
 [0 1 0]
 [0 1 1]
 [1 1 1]]


In [156]:
#两个向量A和B，写出用einsum等式对应的inner, outer, sum, mul函数
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
print ('sum:')
print (np.einsum('i->', A))# np.sum(A)
print ('A * B:')
print (np.einsum('i,i->i', A, B)) # A * B
print ('inner:')
print (np.einsum('i,i', A, B))    # np.inner(A, B)
print ('outer:')
print (np.einsum('i,j->ij', A, B))    # np.outer(A, B)

sum:
4.156946130241224
A * B:
[0.03981526 0.04011964 0.35586015 ... 0.08026855 0.00216258 0.55807994]
inner:
1.427450828386599
outer:
[[0.03981526 0.00372305 0.06683168 ... 0.00606386 0.00879528 0.05687228]
 [0.42904962 0.04011964 0.72017882 ... 0.06534416 0.09477799 0.61285614]
 [0.21200521 0.01982422 0.35586015 ... 0.03228834 0.04683241 0.30282906]
 ...
 [0.52704314 0.04928284 0.8846653  ... 0.08026855 0.11642497 0.75283048]
 [0.00978977 0.00091542 0.01643257 ... 0.00149098 0.00216258 0.01398375]
 [0.39070178 0.03653381 0.65581027 ... 0.05950379 0.08630687 0.55807994]]


In [157]:
#一个由两个向量描述的路径(X,Y)，用等距样例(equidistant samples)对其进行采样(sample)
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

In [158]:
#给定整数n和2维数组X，从X中选择具有n度的多项分布的绘制的行，仅包含整数并且总和为n的行。
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print (X[M])

[[2. 0. 1. 1.]]


In [159]:
 #对于一个一维数组X，计算它boostrapped之后的95%置信区间的平均值。
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print (confint)

[-0.31763394  0.05605336]
